version: 2
workflows:
  version: 2
  build:
    jobs:
      - build
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout
      - run: uname -a
      - run: go version
      - run: go env
      - run: go vet -v ./...
      - run:
          name: golint
          command: |
                    go install golang.org/x/lint/golint@latest
                    golint -set_exit_status ./...
      - run:
          name: staticcheck.io
          command: |
                    go install honnef.co/go/tools/cmd/staticcheck@latest
                    staticcheck -checks all ./...
      - run:
          name: Check gofumpt formatting
          command: |
                    go install mvdan.cc/gofumpt@latest
                    gofumpt -d .
                    [ -z "$(gofumpt -l .)" ]
