version: 2
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          context:
            - docker-credentials
          filters:
            branches:
              only:
                - master
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/go:1.24

    steps:
      - checkout
      - run: make lint

  publish:
    docker:
      - image: cimg/go:1.24

    steps:
      - checkout
      - setup_remote_docker
      - run: make publish-docker
