version: 2
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          context:
            - docker-credentials
          filters:
            branches:
              only:
                - master
  scheduled:
    triggers:
      - schedule:
          cron: "1 2 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/go:1.20

    steps:
      - checkout
      - run: uname -a
      - run: go version
      - run: go env
      - run: go vet -v ./...
      - run:
          name: golint
          command: |
                    go install golang.org/x/lint/golint@latest
                    golint -set_exit_status ./...
      - run:
          name: staticcheck.io
          command: |
                    go install honnef.co/go/tools/cmd/staticcheck@latest
                    staticcheck -checks all ./...
      - run:
          name: Check gofumpt formatting
          command: |
                    go install mvdan.cc/gofumpt@latest
                    gofumpt -d .
                    [ -z "$(gofumpt -l .)" ]
  publish:
    docker:
      - image: cimg/go:1.20

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and publish docker image
          command: |
                    docker build --build-arg GIT_COMMIT=$CIRCLE_SHA1 -t docker.x-way.org/xway/dnsupd:latest .
                    echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin docker.x-way.org
                    docker push docker.x-way.org/xway/dnsupd:latest
