on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  bugsnag:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up BugSnag
        run: curl -o- https://raw.githubusercontent.com/bugsnag/bugsnag-cli/main/install.sh | bash
      -
        name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      -
        name: Upload release information
        run: /home/runner/.local/bugsnag/bin/bugsnag-cli create-build --api-key=${{ secrets.BUGSNAG_API_KEY }} --version-name=${{ github.sha }} --release-stage=production
